.github/workflows/mirror-rolling-to-master.yaml

Relates to: https://gitlab.com/ros-tracing/ros2_tracing/-/issues/144
See: https://discourse.ros.org/t/change-default-branch-name-to-rolling-in-ros-2-core/26009
This exact same file is used by all other repos, e.g.: https://github.com/ros2/rclcpp/blob/b953bdddf8de213b4a051ecf2d668dad65ff9f89/.github/workflows/mirror-rolling-to-master.yaml

Mirror rolling to master

---

.gitlab-ci.yml
README.md
doc/design_ros_2.md
instrumented.repos
ros2trace/package.xml
ros2trace/setup.py
test_tracetools/package.xml
test_tracetools_launch/package.xml
test_tracetools_launch/setup.py
tracetools/Doxyfile
tracetools/QUALITY_DECLARATION.md
tracetools/package.xml
tracetools_launch/package.xml
tracetools_launch/setup.py
tracetools_read/package.xml
tracetools_read/setup.py
tracetools_test/package.xml
tracetools_test/setup.py
tracetools_trace/package.xml
tracetools_trace/setup.py
tracetools_trace/tracetools_trace/tools/lttng.py
tracetools_trace/tracetools_trace/tools/lttng_impl.py
tracing.repos

And update other relevant links.
For the move from GitLab to GitHub, see: https://gitlab.com/ros-tracing/ros2_tracing/-/issues/144#move-checklist

Change repo URL to GitHub & default branch to rolling

---

.github/workflows/dco.yml
.github/workflows/sanity.yml
.github/workflows/test.yml
.gitlab-ci.yml
codecov.yml

This PR configures a GitHub workflow that matches the existing GitLab CI: https://gitlab.com/ros-tracing/ros2_tracing/-/blob/b695e4e367fb6e250d3147ab6b851b25a0e50299/.gitlab-ci.yml. It builds `ros2_tracing` with/without LTTng and with/without tracing being disabled, and checks if the tracing instrumentation is indeed available (or not).
The "sanity checks" workflow makes sure that the tracing instrumentation can be enabled when starting from a default source build or a binary installation, as explained in the build instructions in the README: https://github.com/ros2/ros2_tracing#building. This will also be documented on docs.ros.org, see: https://github.com/ros2/ros2_documentation/pull/2877.

Add GitHub CI config

---

.github/workflows/test.yml

By using the `colcon test` arguments that are used on ci.ros2.org: `--executor sequential --retest-until-pass 2 --ctest-args -LE xfail --pytest-args -m "not xfail"`. Retesting a second time when a test fails should reduce flakyness.

Improve local CI testing config

---

.github/workflows/sanity.yml
.github/workflows/test.yml

Otherwise binary jobs can fail if breaking-ish changes are introduced, since we still build part of the code from source.

Use binaries from pre-release/testing apt repository

---

.github/workflows/sanity.yml
.github/workflows/test.yml

Possible alternative to #8. This should allow other jobs to keep running (and not get cancelled) even if the binary jobs fail. Hopefully the binary jobs somehow fix themselves soon.

Disable fail-fast in CI configs

---

.github/workflows/sanity.yml

Follow-up to #9, I missed this.

Enable 'continue-on-error' for sanity checks job too

---

tracetools_test/tracetools_test/case.py

Relates to #27
This fixes mypy errors for a more recent version of mypy compared to the system version on Ubuntu 22.04. Therefore, while this isn't really necessary, I think it's still useful.

Fix mypy errors

---

tracetools_launch/tracetools_launch/action.py
tracetools_trace/tracetools_trace/tools/lttng_impl.py
tracetools_trace/tracetools_trace/trace.py

Closes #37
The `context_names` parameter was deprecated and replaced with `context_fields` in Rolling before the Humble release, so we can remove it now.
I've also changed "names" to "fields" in a printed message.

Remove deprecated context_names parameter

---

README.md
doc/design_ros_2.md
tracing.repos

Part of https://gitlab.com/ros-tracing/tracetools_analysis/-/issues/55

Update links to tracetools_analysis repo

---

tracetools/include/tracetools/tracetools.h
tracetools/src/tracetools.c

This adds the `TRACEPOINT_ENABLED()` and `DO_TRACEPOINT()` macros alongside the current `TRACEPOINT()` macro. These `tracetools` macros correspond to LTTng's `tracepoint_enabled()`, `do_tracepoint()`, and `tracepoint()` macros, respectively. See [lttng-ust(3)](https://lttng.org/man/3/lttng-ust/v2.13/).
During runtime, this allows first checking if the tracepoint is enabled before doing some processing and triggering the tracepoint manually. This way, we avoid doing unnecessary processing/memory allocations/etc. if the tracepoint isn't enabled.
Eventually, for tracers that do not support this mechanism, we can just `#define TRACEPOINT_ENABLED(...) true` and `#define DO_TRACEPOINT(...) TRACEPOINT(__VA_ARGS__)`.

Add TRACEPOINT_ENABLED() and DO_TRACEPOINT() macros

---

test_tracetools/test/test_utils.cpp
tracetools/include/tracetools/utils.hpp
tracetools/src/utils.cpp

Fixes #34
`tracetools::get_symbol()` is used to get a demangled symbol from a function pointer or `std::function` object. This is used to associate a human-readable string to a callback in the trace data. To do symbol demangling, it calls [`abi::__cxa_demangle()`, which returns a pointer that must be freed by the caller](https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a01696.html). This was never freed. The best solution would be to use a limited size buffer on the stack and never allocate. However, while `abi::__cxa_demangle` _can_ accept a pre-allocated buffer, it cannot be on the stack, since `abi::__cxa_demangle` expands it using `realloc` if it is not long enough.
Since the pointer to the demangled symbol must be freed, the problem is that `tracetools::get_symbol()` …

Fix memory leak in tracetools::get_symbol()

---

tracetools/CMakeLists.txt

Fix regression introduced by #43 on RHEL.
It looks like we need to explicitly link against dl on RHEL. Note that, if `TRACETOOLS_LTTNG_ENABLED`, LTTng's link flags already include `-ldl`.

Explicitly link against dl for dladdr()

---

tracetools_launch/package.xml
tracetools_trace/tracetools_trace/tools/lttng_impl.py
tracetools_trace/tracetools_trace/trace.py

Fix missing `exec_depends` in `package.xmls` and docstrings to generate documentation without any warnings using `autodoc`
>Note: Without explictly casting `lttng.__doc__` to string, `autodoc` cannot infer it's type since dep modules are not imported.

Enable document generation using rosdoc2 for ament_python pkgs

---

test_tracetools/CMakeLists.txt
tracetools/CMakeLists.txt

Fixes #52
Prior to #31, `tracetools` tried to look for LTTng-UST on macOS and Linux, and just disabled tracing if it wasn't found. However, LTTng-UST is now required. Just like we do for Windows, just disable tracing and don't try to look for LTTng on macOS.

Disable tracing on macOS

---

tracetools/Doxyfile
tracetools/include/tracetools/tracetools.h

This documents the new `TRACEPOINT_ENABLED()`/`DO_TRACEPOINT()` macros.
This also modifies `tracetools`' `Doxyfile` to improve the `rosdoc2` output. I excluded a bunch of internal macros. Unfortunately, due to the macro wizardry with the tracepoint declarations in `tracetools.h` (see `DECLARE_TRACEPOINT()`), I can't quite get Doxygen to detect the generated functions for the tracepoints properly, so the generated documentation unfortunately does not list the tracepoints. It's at least better than the current output, which is pretty useless: https://docs.ros.org/en/humble/p/tracetools/generated/index.html

Improve tracetools rosdoc2/doxygen output

---

test_tracetools/test/test_executor.py
test_tracetools/test/test_intra.py
test_tracetools/test/test_lifecycle_node.py
test_tracetools/test/test_node.py
test_tracetools/test/test_pub_sub.py
test_tracetools/test/test_publisher.py
test_tracetools/test/test_service.py
test_tracetools/test/test_subscription.py
test_tracetools/test/test_timer.py
test_tracetools_launch/test/test_tracetools_launch/test_trace_action.py
tracetools_trace/test/tracetools_trace/test_lttng_tracing.py
tracetools_trace/tracetools_trace/tools/lttng.py

Closes #16
This changes `is_lttng_installed()` to also check for the `lttng` Python package.
This also adds an optional `minimum_version` parameter to `is_lttng_installed()` to check if the `lttng` Python package version is sufficient. This is then used to ignore some tests which require `lttng.BUFFER_*`, which isn't available until version 2.9. RHEL 8 has LTTng 2.8, so those tests fail. With this change, tests run successfully on RHEL 8, or, rather, the tests that can't run are skipped.

Allow requiring minimum lttng package version for is_lttng_installed

---

ros2trace/package.xml
ros2trace/ros2trace/command/trace.py
ros2trace/test/ros2trace/test_trace.py
tracetools_launch/tracetools_launch/action.py
tracetools_trace/test/tracetools_trace/test_lttng_tracing.py
tracetools_trace/tracetools_trace/tools/lttng.py
tracetools_trace/tracetools_trace/tools/lttng_impl.py
tracetools_trace/tracetools_trace/trace.py

Closes #26
Closes #36
This improves error handling and error report in `tracetools_trace`. The common functions used by `ros2trace` (for the `ros2 trace` command) and `tracetools_launch` (for the `Trace` launch action) now do not print anything; they raise exceptions where appropriate. Then, `ros2 trace`/`Trace` can catch any error and report it using the appropriate method: print to `stderr` for `ros2 trace` and log error for `Trace`.
This also makes sure to destroy the tracing session if it exists when tracing configuration fails.
Finally, this adds end-to-end tests for the `ros2 trace` command to cover the main cases. It also improves parameter validation for the session name.

Improve 'ros2 trace' command error handling & add end-to-end tests

---

ros2trace/test/ros2trace/test_trace.py
test_tracetools_launch/test/test_tracetools_launch/test_trace_action.py
tracetools_launch/tracetools_launch/action.py
tracetools_trace/tracetools_trace/tools/args.py
tracetools_trace/tracetools_trace/tools/lttng_impl.py
tracetools_trace/tracetools_trace/trace.py

Closes #12
This makes the `ros2 trace` command and the `Trace` launch action fail if the trace already exists, unless the `--append-trace` or `append_trace`/`append-trace` option is used, respectively. Example:
```sh
$ ros2 trace -s 'my-trace'  # Generate trace
UST tracing enabled (28 events)
kernel tracing disabled
context (3 fields)
writing tracing session to: /home/chris/.ros/tracing/my-trace
press enter to start...
press enter to stop...
stopping & destroying tracing session
$ ros2 trace -s 'my-trace'  # Mistakenly append to existing trace, error out
UST tracing enabled (28 events)
kernel tracing disabled
context (3 fields)
writing tracing session to: /home/chris/.ros/tracing/my-trace
press enter to start...
error: trace directory already exists, use the append option to append to it: …
```

Error out if trace already exists unless 'append' option is used

---

.github/workflows/sanity.yml

Follow-up to #31 now that the Rolling binaries include tracepoints.

Expect binaries to include tracepoints in sanity check CI job

---

test_tracetools/test/test_subscription.py
test_tracetools/test/test_timer.py

It wasn't properly tested for subscriptions and timers.

Improve test coverage of rclcpp_callback_register in test_tracetools

---

README.md
ros2trace/ros2trace/command/trace.py
ros2trace/ros2trace/verb/__init__.py
ros2trace/ros2trace/verb/pause.py
ros2trace/ros2trace/verb/resume.py
ros2trace/ros2trace/verb/start.py
ros2trace/ros2trace/verb/stop.py
ros2trace/setup.py
test_ros2trace/test/test_ros2trace/test_trace.py
tracetools_trace/tracetools_trace/tools/args.py
tracetools_trace/tracetools_trace/tools/lttng.py
tracetools_trace/tracetools_trace/trace.py

Closes #68
That adds the following sub-commands to `ros2 trace` as "verbs":
* `ros2 trace start`: configure tracing session and start tracing
* `ros2 trace pause`: stop tracing, without removing tracing session
* `ros2 trace resume`: start tracing again
* `ros2 trace stop`: stop tracing and destroy tracing session
The goal is to provide non-interactive & finer-grained ways to control tracing. For example, this could be used in scripts. It could also be used for long-term tracing (related to #44): users can trace the first 10-30 seconds to collect initialization information, then pause, and then resume tracing again later on.
Example:
```
$ ros2 trace start my_session
UST tracing enabled (35 events)
kernel tracing disabled
context (3 fields)
writing tracing session to: …
```

Create start/pause/resume/stop sub-commands for 'ros2 trace'

---

.github/workflows/sanity.yml
.github/workflows/test.yml

Closes #27
This is no longer necessary after https://github.com/ros-tooling/setup-ros/pull/593. This PR wraps up #27.

Unpin mypy in GitHub CI

---

tracetools_launch/tracetools_launch/actions/ld_preload.py

This can be seen in the test output for `test_tracetools_launch`:
```
test/test_tracetools_launch/test_trace_action.py::TestTraceAction::test_action_ld_preload [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[INFO] [launch]: All log files can be found below /home/christophe.bedard/.ros/log/2023-08-30-14-54-14-398230-ul-pa-1255-1-1810625
[INFO] [launch]: Default logging verbosity is set to DEBUG
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f6fd7b98ee0>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f6fd7b98ee0>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription …
```

Remove extra single quote in LdPreload debug log

---

test_tracetools/CMakeLists.txt
test_tracetools/package.xml

While we are in here, mark all dependencies as test_depend (since this is a test-only package).

Switch to target_link_libraries in test_tracetools.

---

lttngpy/CMakeLists.txt

Closes #86
I found this fix in a few other packages that use Python in CMake.

Fix Python not being found for lttngpy in Windows debug mode

---

tracetools/include/tracetools/tp_call.h
tracetools/include/tracetools/tracetools.h
tracetools/src/tracetools.c

See https://github.com/ros2/ros2_tracing/issues/73
Corresponding `rmw` implementation PRs:
* https://github.com/ros2/rmw_cyclonedds/pull/454
* https://github.com/ros2/rmw_fastrtps/pull/694
* https://github.com/ros2/rmw_connextdds/pull/120
action-ros-ci-repos-override: https://gist.githubusercontent.com/christophebedard/124d8311bed71f7820a2185ce0a25cc3/raw/49c81e6cacce1a5e621ed3880b205dac9096a3ac/ros2.repos

Add timestamp to rmw_publish tracepoint

---

tracetools_trace/tracetools_trace/tools/lttng_impl.py

This will fix a flake8 warning on newer versions.

Add a space in between not and parentheses.

---

tracetools_launch/launch/example.launch.py
tracetools_launch/test/tracetools_launch/test_ld_preload_action.py

For reasons I admit I don't understand, when using mypy 1.8.0 with this code it fails to determine that it can import submodules from launch properly.  Since we can easily workaround this by just doing 'import launch', do that here.

Fix warnings when using mypy 1.8.0.

---

doc/design_ros_2.md
test_tracetools/test/test_pub_sub.py
test_tracetools/test/test_publisher.py
tracetools/include/tracetools/tp_call.h
tracetools/include/tracetools/tracetools.h
tracetools/src/tracetools.c

Follow-up to #74
Relates to #73
1. Update tests to cover the `rmw_publish` tracepoint's new handle and timestamp fields
* Check that the timestamps match between the publication and taking of the same message
2. Update design doc
3. Rename `rmw_publish` tracepoint's `publisher_handle` field to `rmw_publisher_handle`, since it's an `rmw` handle and we use this name for `rmw` handles everywhere else 
* And update arguments doc in `tracetools.h`

Update tests and docs after new rmw_publish timestamp field

---

test_tracetools_launch/test/test_tracetools_launch/test_trace_action.py
tracetools_launch/tracetools_launch/action.py
tracetools_trace/tracetools_trace/tools/lttng_impl.py

Provide a bit more information in error messages.
Also, add a test for invalid context domains with the `Trace` action.

Improve tracing configuration error reporting

---

tracetools_launch/tracetools_launch/action.py
tracetools_launch/tracetools_launch/actions/ld_preload.py

Using a single underscore for private variables is usually recommended: https://google.github.io/styleguide/pyguide.html#3162-naming-conventions

Use single underscore for private vars in Python

---

test_tracetools/test/test_buffer.py
test_tracetools/test/test_intra.py
test_tracetools/test/test_intra_pub_sub.py
test_tracetools/test/test_lifecycle_node.py
test_tracetools/test/test_pub_sub.py
test_tracetools/test/test_publisher.py
test_tracetools/test/test_service.py
test_tracetools/test/test_subscription.py
test_tracetools/test/test_timer.py
tracetools_test/tracetools_test/case.py

This is in the context of tracing tests failing on ROS 2 CI after parallelized testing was enabled. The goal is to improve the failed assertion messages to better understand how/why the tests failed just by looking at the test logs, which should hopefully help us fix the tests.
To do this, I:
1. Improved some of the default messages in `TraceTestCase`'s `assert*()` methods to include more information, like the full event(s) data, the field name(s), and the value(s) (if applicable).
2. Removed some of the assert messages in the tests to rely on the default ones. Most (if not all) messages didn't contain the actual event data or value, which is really the part that's useful. The messages only explained the context, which we can figure out by looking at the code anyway, so it wasn't really …

Make tracing test assert messages more descriptive

---

test_tracetools/test/test_lifecycle_node.py
tracetools_test/tracetools_test/case.py
tracetools_test/tracetools_test/utils.py

Part of #94
Relates to #95, but is still separate
`test_tracetools`'s `test_lifecycle_node` test and [`ros2lifecycle`'s `test_cli` test](https://github.com/ros2/ros2cli/blob/64d216cb8fafef83d046b79ee6294afb06b7c595/ros2lifecycle/test/test_cli.py) can interfere with each other if run in parallel, making one of them -- or both of them -- fail. For example, `test_tracetools` fails in this nightly job here: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2988/.
This is mainly because both tests use a lifecycle node with the same name and without any specific namespace:
1. `test_tracetools`'s `test_lifecycle_node` test uses [`test_lifecycle_node`](https://github.com/ros2/ros2_tracing/blob/9a807801f3608f937a3725dc6723a9ac417d670c/test_tracetools/src/test_lifecycle_node.cpp)
2. …

Fix interference between test_tracetools and ros2lifecycle tests

---

test_ros2trace/package.xml
test_ros2trace/test/test_ros2trace/test_trace.py
test_tracetools/CMakeLists.txt
test_tracetools/include/test_tracetools/mark_process.hpp
test_tracetools/package.xml
test_tracetools/src/mark_process.cpp
test_tracetools/src/test_intra.cpp
test_tracetools/src/test_lifecycle_client.cpp
test_tracetools/src/test_lifecycle_node.cpp
test_tracetools/src/test_ping.cpp
test_tracetools/src/test_pong.cpp
test_tracetools/src/test_publisher.cpp
test_tracetools/src/test_service.cpp
test_tracetools/src/test_service_ping.cpp
test_tracetools/src/test_service_pong.cpp
test_tracetools/src/test_timer.cpp
tracetools_read/tracetools_read/__init__.py
tracetools_test/tracetools_test/case.py
tracetools_test/tracetools_test/mark_process.py
tracetools_test/tracetools_test/utils.py

Resolves #94
This allows tracing tests to be run in parallel with (a) other tracing tests (e.g., from another package) and (b) normal tests (e.g., any ROS 2 tests). It achieves that by doing two things in two separate commits:
1. Only consider test trace data corresponding to the current test
1. If we configure tracing in a tracing test and other tests (and therefore "ROS 2 applications") run in parallel, we will collect trace data from all running applications and end up with irrelevant data. #94 provides an overview of the possible solutions along with pros and cons. The chosen (and most robust) solution is:
1. The tracing test passes a trace test ID to the test application processes it spawns through an environment variable
1. The trace test ID contains the tracing test's PID and the …

Allow tracing tests to be run in parallel with other tests

---

test_tracetools/src/mark_process.cpp

It turns out that in the older version of lttng-ust on RHEL-9, the API to set a marker is spelled _lttng_ust_tracef.  Include the correct version header file, and use the correct API called depending on what version we are using.
This is a follow-up to the recently merged #96 , where I forgot to run RHEL CI before merging.

Fix the build on RHEL-9.

---

test_tracetools/test/test_utils.cpp

I believe that g++ does not guarantee what a particular symbol name will be.  Thus, in g++ 11.4.0 (what is in Ubuntu 22.04), the symbol name here ended with "#2", while in g++ 13.2.0 (what is in Ubuntu 24.04), the symbol name ends with "#1".  Given that we can't guarantee this, just search for the first part of the name up to the number, which should be good enough for this test.

Use a memcmp for the expected symbol name.

---

test_tracetools/src/mark_process.cpp

Follow-up to #95
Follow-up to #98
The "official" symbol that the LTTng documentation mentions is:
1. \>=2.13: `lttng_ust_tracef()`, not `lttng_ust__tracef()`
1. Docs: https://lttng.org/docs/v2.13/#doc-tracef
2. Code: https://github.com/lttng/lttng-ust/blob/2e8e974039487cb8b2b22dc01ffdd6c9931ec02b/include/lttng/tracef.h#L23
2. <=2.12: `tracef()`, not `_lttng_ust_tracef()`
1. Docs: https://lttng.org/docs/v2.12/#doc-tracef
2. Code: https://github.com/lttng/lttng-ust/blob/6b0c6b76480d8162cb00919367cc2d13ccbe7037/include/lttng/tracef.h#L35
I thought that the difference between them is that the former checks if the tracepoint is enabled before triggering the tracepoint, while the latter just triggers it, but that is not the case. We can observe this by not enabling `lttng_ust_tracef:event` in …

Use lttng_ust_tracef instead of lttng_ust__tracef

---

tracetools_test/tracetools_test/case.py

Make the output in case of failure a bit more helpful by relying on `self.assertListEqual`, which shows a somewhat-helpful diff.
Also, optimize `are_events_ordered()` a bit.

Improve assertEventOrder failure output

---

test_tracetools/CMakeLists.txt
test_tracetools/src/test_generic_ping.cpp
test_tracetools/src/test_generic_pong.cpp
test_tracetools/test/test_generic_pub_sub.py
test_tracetools/test/test_generic_subscription.py

Please, refer to  https://github.com/ros2/rclcpp/pull/2448.
Because I added tracepoint for GenericPublisher and GenericSubscriber, I add some tests to test_tracetools.
I have added the following tests.
- src/
- test_generic_ping.cpp
- test_generic_pong.cpp
- test/
- test_generic_pub_sub.py
- test_generic_subscription.py
action-ros-ci-repos-override: https://gist.githubusercontent.com/christophebedard/9a37e393935913add5ad490aaee26e7f/raw/194c464b68cd138e887f041f50f42c0cbe3f4710/ros2.repos

Add test for GenericPublisher/Subscriber

---

test_ros2trace/test/test_ros2trace/test_trace.py

The `test_unknown_context_field` test expected an error on unknown context fields, but there was no test for a normal/non-error case.
Also, modify `assertTraceContains` to be able to expect fields.

Add explicit context fields test to test_ros2trace

---

test_tracetools/test/test_intra.py

I think this was left over from when I first wrote the test.

Remove unnecessary print in test

---

test_tracetools/src/mark_process.cpp

Include <string> in mark_process.cpp

---

test_tracetools/CMakeLists.txt

This is needed if the `build/` directory is not available when running the `test_tracetools` tests.

Install test_tracetools_mark_process

---

test_tracetools/test/test_buffer.py
test_tracetools/test/test_generic_pub_sub.py
test_tracetools/test/test_generic_subscription.py
test_tracetools/test/test_intra.py
test_tracetools/test/test_intra_pub_sub.py
test_tracetools/test/test_lifecycle_node.py
test_tracetools/test/test_pub_sub.py
test_tracetools/test/test_publisher.py
test_tracetools/test/test_service.py
test_tracetools/test/test_subscription.py
test_tracetools/test/test_timer.py
tracetools_read/tracetools_read/__init__.py
tracetools_test/tracetools_test/case.py

The main/biggest improvement is the new `get_event_with_field_value_and_assert()` test method, which can simplify this very common bit of code:
```py
my_events = self.get_events_with_field_value('field', value, events)
self.assertNumEventsEqual(my_events, 1)
my_event = my_events[0]
```
into:
```py
event = self.get_event_with_field_value_and_assert('field', value, events)
```
I've therefore updated a lot of test code to use this new assert method, which makes it a lot simpler and smaller.
I also renamed `assertValidArray()` to `assertValidStaticArray()` and added length checking.

Improve tracetools_test and simplify test_tracetools code

---

tracetools/CMakeLists.txt
tracetools/include/tracetools/tp_call.h
tracetools/package.xml

Instead of manually defining a private compile definition.

Switch to ament_generate_version_header for tracetools

---

.github/workflows/sanity.yml
.github/workflows/test.yml

* The `ubuntu-24.04` GitHub actions runner might not be available until August 2024 (https://github.com/actions/runner-images/issues/9691), so just use Docker
* We seem to now need to explicitly set the default shell to bash to get `source` to work (possibly due to running in Docker and not the runner itself)

Use Ubuntu 24.04 Noble for GitHub CI

---

tracetools/include/tracetools/tp_call.h

While trying to compile ros2 on my system with gcc-14 i got an integer conversion warning causing a compilation failure:
```bash
error: initialization of ‘const uint64_t *’ {aka ‘const long unsigned int *’} from ‘uint64_t’ {aka ‘long unsigned int’} makes pointer from integer without a cast [-Wint-conversion]
474 |     ctf_integer(const uint64_t *, index, index_arg)
```
As far as i see it, the field type should match the argument type in this case.
After applying the proposed fix locally, the compilation succeeded.

tp_call.h fix field type for tracepoint event rclcpp_ring_buffer_enqueue

---

.github/workflows/dco.yml
.github/workflows/sanity.yml
.github/workflows/test.yml

This takes care of some deprecation warnings.

Bump versions of actions in GitHub CI

---

test_tracetools/CMakeLists.txt
test_tracetools/package.xml
tracetools_test/tracetools_test/case.py

The `test_tracetools` tracing tests only currently run using the default `rmw` implementation. However, all "main" `rmw` implementations are instrumented, so we should run the tests that cover `rmw` instrumentation against all supported implementations.
Requires #104 for CI to pass.

Run relevant test_tracetools tests with all instrumented rmw impls

---

tracetools/Doxyfile
tracetools/include/tracetools/tracetools.h

These macros were deprecated in #56 for Jazzy. Now that Jazzy has been released, remove them completely.

Remove deprecated TRACEPOINT macros

---

test_tracetools/src/test_generic_ping.cpp
test_tracetools/src/test_generic_pong.cpp
test_tracetools/src/test_ping.cpp
test_tracetools/src/test_pong.cpp

Fixes #124
See an overview of the tests in https://github.com/ros2/ros2_tracing/issues/124#issuecomment-2207132572
This will make sure that the initial `/ping` message is received no matter the launch order of the `*ping` and `*pong` executables.
Also, given this guarantee, cancel the timer after the initial `/ping` message.
Finally, add some helpful debug logs.

Make test_tracetools ping pubs/subs transient_local

---

tracetools/include/tracetools/tp_call.h
tracetools/src/tracetools.c

Fixes #105
The warnings are due to the lttng-ust macros. While the relevant `tracetools` macros have two variants to handle tracepoints _with_ and _without_ arguments (see comment in `tracetools.h`), the lttng-ust macros do not:
```c
#define lttng_ust_do_tracepoint(provider, name, ...)
```
This will be called without any variadic arguments by the `tracetools` `_CONDITIONAL_DO_TP()` macro (see `tracetools.c`). For example, in rough order of expansion:
```c
// 1.
DEFINE_TRACEPOINT_NO_ARGS(
rclcpp_executor_get_next_ready)
// 2.
_CONDITIONAL_DO_TP(rclcpp_executor_get_next_ready)
// 3.
do_tracepoint(ros2, rclcpp_executor_get_next_ready)
// 4.
lttng_ust_do_tracepoint(ros2, rclcpp_executor_get_next_ready)
```
Therefore, ignore the `gnu-zero-variadic-macro-arguments` warning with clang in …

Ignore zero-variadic-macro-arguments warnings from lttng-ust macros

---

README.md
test_tracetools/CMakeLists.txt

This is sort of a follow-up to #116, see https://github.com/ros2/ros2_tracing/pull/116#discussion_r1645042581
Requires https://github.com/ros2/rmw_fastrtps/pull/772 for the `rmw_fastrtps_dynamic_cpp` tracing instrumentation
action-ros-ci-repos-override: https://gist.githubusercontent.com/christophebedard/c07fa52c22a5d4af1c0b88755409344b/raw/a0d726f66dcca91cb26b77ef5ef3e35a135ed9e2/ros2.repos

Run test_tracetools tests against rmw_fastrtps_dynamic_cpp too

---

lttngpy/package.xml

The `lttngpy` package depends on `pkg-config` for finding the `lttng-ctl` libraries, but didn't list it in its `package.xml`. Without the explicit dependency, some strict build environments will fail.

Add missing dependency on pkg-config to lttngpy

---

README.md
lttngpy/src/lttngpy/_lttngpy_pybind11.cpp
lttngpy/src/lttngpy/event.cpp
lttngpy/src/lttngpy/event.hpp
test_ros2trace/test/test_ros2trace/test_trace.py
test_tracetools_launch/test/test_tracetools_launch/test_trace_action.py
tracetools_launch/tracetools_launch/action.py
tracetools_trace/test/tracetools_trace/test_lttng_tracing.py
tracetools_trace/tracetools_trace/tools/args.py
tracetools_trace/tracetools_trace/tools/lttng_impl.py
tracetools_trace/tracetools_trace/trace.py

This adds support for enabling syscall tracing with the `ros2 trace` command or the `Trace` launch action.
While system calls are separate from kernel events, both can be traced using the LTTng kernel tracer: https://lttng.org/docs/v2.13/#doc-tracing-the-linux-kernel. Kernel events are "tracepoints" while system calls are their own kind of trace event. This explains why this PR adds a separate option for syscalls instead of just using the kernel events option. See the changes to `lttngpy::enable_events` in `lttngpy/src/lttngpy/event.cpp`.
How to use:
1. `ros2 trace` command:
```
$ ros2 trace --syscall openat  # interactive
$ ros2 trace start my-session-name --syscall openat  # non-interactive
```
2. Launch files (Python, XML, and YAML): `syscalls` arg
Note that, when enabling a syscall, …

Allow enabling syscalls through `ros2 trace` or the Trace action

---

test_tracetools/test/test_generic_subscription.py
test_tracetools/test/test_publisher.py
test_tracetools/test/test_subscription.py
tracetools/include/tracetools/tp_call.h

The size changed from 24 to 16 bytes in ros2/rmw#345. The same size is defined in `tracetools`, and it was never updated.
In practice, reading 24-16=8 random extra bytes didn't change much, since nothing is currently relying on the GID values, at least not relying on getting the same GID for the same object from two different systems, because it doesn't work with `rmw_cyclonedds`, see ros2/rmw_cyclonedds#377.

Change expected rmw GID array size to 16 bytes
